### ISSUE TITLE
Selection of Pt function

### ISSUE THREAD

**Issue by krmui** [JeyesHan/P2LR#4]
I'm sorry to bother you again，I would like to ask whether your selection function of Pt is determined by trial and error, or by referring to other literature?

**Comment by HelloJianHan** [comment]
We adopt Pt function to ensure that more (new) samples join in the training in early steps since there are easier samples at the begining. As the training goes, newly selected samples become harder and we incorporate less ones to make them fully trained. Therefore, we design Pt as the rescaled log-exp funciton with some hyper-parameters. Those hyper-parameters are tuned based on experimental results.
