### ISSUE TITLE
请问是否可以公布weights文件，想基于本工作在模型推理加速方面进行探索

### ISSUE THREAD

**Issue by mookixiao** [JeyesHan/P2LR#6]
我想基于本工作在端侧模型推理加速方面进行探索，但是目前在复现论文精度方面有困难
所以想请问是否可以公布weights文件？

**Comment by HelloJianHan** [comment]
Of course. However, I have already graduated and am working full-time now. It's quite busy for my office hours. I will find the weights during my free time this week and upload it. Please be patient.

**Comment by HelloJianHan** [comment]
Here are duke2market pretrained weights:
https://drive.google.com/file/d/1r3Vn8aVjSX-mRKkerFG8ApL6cPVRE1lE/view?usp=sharing
Other weights I will find them and upload it during my free time this week.

**Comment by HelloJianHan** [comment]
The weights:
https://drive.google.com/file/d/1K9Wi0WVKearzgzCBA_NLsKon6WFtDWG5/view?usp=sharing
In fact, I reproduced them because I couldn't find the original weights due to graduation. However, it was simple to reproduce with 4 GPUs, and I achieved an mAP of 81.4 on the Duke2Market benchmark. It is slightly better than the results mentioned in the paper (81.0).

**Comment by mookixiao** [comment]
> The weights: https://drive.google.com/file/d/1K9Wi0WVKearzgzCBA_NLsKon6WFtDWG5/view?usp=sharing In fact, I reproduced them because I couldn't find the original weights due to graduation. However, it was simple to reproduce with 4 GPUs, and I achieved an mAP of 81.4 on the Duke2Market benchmark. It is slightly better than the results mentioned in the paper (81.0).

Got it, thanks for your help. 😄
